services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: hack_zurich
      POSTGRES_USER: hack_zurich
      POSTGRES_PASSWORD: hack_zurich
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 5432:5432
    # volumes:
    #   - ./data/hack_zurich:/var/dumps

  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080
    links:
      - postgres
